services:
  - type: web
    name: API_Domino
    runtime: python
    env: python
    region: ohio
    plan: free
    autoDeploy: false  # Désactive le déploiement automatique global
    buildCommand: |
      cd API_Domino
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: cd API_Domino && daphne -b 0.0.0.0 -p $PORT API_Domino.asgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false
      - key: DEBUG
        value: "False"

  - type: worker
    name: API_Domino_Celery
    runtime: python
    env: python
    region: ohio
    plan: free
    autoDeploy: false  # Désactive le déploiement automatique global
    buildCommand: |
      cd API_Domino
      pip install -r requirements.txt
    startCommand: cd API_Domino && celery -A API_Domino worker --loglevel=info
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        sync: false
