# Generated by Django 5.1.5 on 2025-01-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_remove_game_round_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domino',
        ),
        migrations.RemoveField(
            model_name='session',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='round',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='gametable',
            name='last_player',
        ),
        migrations.RemoveField(
            model_name='gametable',
            name='round',
        ),
        migrations.RemoveField(
            model_name='gametable',
            name='session',
        ),
        migrations.AlterUniqueTogether(
            name='infosession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='infosession',
            name='player',
        ),
        migrations.RemoveField(
            model_name='infosession',
            name='session',
        ),
        migrations.RemoveField(
            model_name='infosession',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='round',
            name='player',
        ),
        migrations.RemoveField(
            model_name='session',
            name='hote',
        ),
        migrations.RemoveField(
            model_name='round',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='session',
            name='statut',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Gametable',
        ),
        migrations.DeleteModel(
            name='Infosession',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Statut',
        ),
    ]
