# Generated by Django 5.1.5 on 2025-01-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HandPlayer',
        ),
    ]
