# Generated by Django 5.1.5 on 2025-01-29 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_delete_handplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominoes', models.TextField()),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='authentification.player')),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentification.round')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.session')),
            ],
            options={
                'db_table': 'HandPlayer',
            },
        ),
    ]
