# Generated by Django 5.1.5 on 2025-01-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_handplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round_count',
            field=models.IntegerField(default=1),
        ),
    ]
