# Generated by Django 5.1.5 on 2025-02-01 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_alter_game_round_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='statut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentification.statut'),
        ),
    ]
