# Generated by Django 5.1.5 on 2025-02-02 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_round_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handplayer',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.round'),
        ),
    ]
