# Generated by Django 5.1.5 on 2025-02-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_alter_handplayer_round'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='last_player',
            new_name='player_turn',
        ),
    ]
