# Generated by Django 5.1.5 on 2025-02-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0010_rename_last_player_round_player_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='handplayer',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
