# Generated by Django 5.1.5 on 2025-02-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0011_handplayer_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.TextField(default='Un-named session', max_length=30),
            preserve_default=False,
        ),
    ]
